### ISSUE TITLE
게시물 조회시 secretFlag

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-BE-Spring#110]
## Describe the bug
> 어떤 버그인지 설명해주세요.

- 건의사항의 게시물 조회시 secretFlag 가 false임을 확인했습니다.

## To Reproduce
> 버그를 재현하는 과정을 설명해주세요.
![K-004](https://user-images.githubusercontent.com/33450285/156912533-7449e766-7dd8-4544-8b0e-c23b8465c1ff.png)

1. 건의사항에서 글 작성(이때는 비밀글로 설정할 수 있습니다.)
2. 게시글 들어간 후 게시물 조회 api 요청
3. 리턴값을 확인시  secretFlag = false.

## Expected behavior
> 기대하는 결과를 설명해주세요.

- 비밀글이 가능한 게시판의 경우,  secretFlag = true 로 정상작동

**Comment by imgzon3** [comment]
게시판 조회 api를 호출할 경우, 비밀글이 가능한 게시판일 경우 secretFlag = true로 나오도록 변경해 두었습니다.
게시물 조회 시에는 **비밀글이 가능**인 경우가 아닌 **비밀글인 경우**를 secretFlag로 나타냅니다.

즉, 게시물 조회 시 게시물이 비밀글이라면 secretFlag = true로 반환됩니다.

**Comment by dmdgpdi** [comment]
이해했습니다. 이에 맞게 수정하겠습니다.
