### ISSUE TITLE
이미지 파일 첨부시 다운로드 문제

### ISSUE THREAD

**Issue by dmdgpdi** [WeGrus/WeGrus-BE-Spring#98]
## Describe the bug
> 어떤 버그인지 설명해주세요.

- 이미지 파일을 업로드한 뒤 다운로드를 하면 이미지가 다운되지않고 이미지 파일이 있는 주소로 이동하게 됩니다.

### Screenshots (Optional)
![K-110](https://user-images.githubusercontent.com/33450285/154795766-eff2b58f-0684-4de5-b283-32f94e8c47a5.png)

## To Reproduce

> 버그를 재현하는 과정을 설명해주세요.

1. 이미지 파일 업로드 된 게시글에서 파일 첨부 클릭
2. 이미지가 있는 곳으로 이동

## Expected behavior
> 기대하는 결과를 설명해주세요.

- 이미지 파일도 정상적인 다운로드가 된다.

**Comment by imgzon3** [comment]
기존 aws 서버에 저장된 url 보내주기 -> 백엔드에서 파일을 다운받은 후, 전달해주기로 수정해보겠습니다
